version: "3"
services:
  app:
    # build:
    #   dockerfile: Dockerfile
    image: golang:1.18-alpine
    working_dir: /opt/product
    container_name: product
    # restart: unless-stopped
    # env_file:
    #   - .env.dev
    ports:
      - 8827:8827
    volumes:
      - ./:/opt/product
    stdin_open: true
    command: go run main.go
    networks:
      - jaybod_network
networks:
  jaybod_network:
    name: jaybod_network